Repository cosmos/interchain-security, pull requests merged in 2023-07, with the labels that each got.

#1097 fix: `AttributeDistributionTotal` in event emit
  CHANGELOG.md
  x/ccv/consumer/keeper/distribution.go
Labels: A:backport/v2.0.x, A:backport/v3.0.x

#1121 chore: add cometbft bump PR info to changelog
  CHANGELOG.md
Labels: documentation, A:backport/v3.0.x

#1138 docs: clean changelog for v3.1.0
  CHANGELOG.md
Labels: A:backport/v3.1.x

#1130 docs: update broken md links
  docs/docs/features/proposals.md
  docs/docs/validators/joining-testnet.md
Labels: A:backport/v2.0.x, A:backport/v3.0.x, A:backport/v3.1.x

#1156 fix: update broken .dependabot.yml
  .github/dependabot.yml
Labels: bug
