Repository cosmos/interchain-security, pull requests merged in 2023-06, with the labels that each got.

#999 docs: Increase the validator set of cosmos hub to 180 from 175
  docs/docs/validators/overview.md
Labels: documentation

#1004 fix: limit vsc matured packets handled per endblocker
  CHANGELOG.md
  tests/integration/throttle.go
  testutil/integration/debug_test.go
  x/ccv/provider/keeper/relay.go
  x/ccv/provider/keeper/throttle.go
  x/ccv/provider/keeper/throttle_test.go
  x/ccv/provider/types/keys.go
  x/ccv/provider/types/keys_test.go
Labels: A:backport/v2.0.x

#1056 docs: add v3.0.0 changelog
  CHANGELOG.md
Labels: A:backport/v3.0.x

#1060 fix: re-enable make proto-check and update proto options
  .github/workflows/automated-tests.yml
  Makefile
  proto/interchain_security/ccv/consumer/v1/consumer.proto
  proto/interchain_security/ccv/consumer/v1/genesis.proto
  proto/interchain_security/ccv/consumer/v1/query.proto
  proto/interchain_security/ccv/provider/v1/genesis.proto
  proto/interchain_security/ccv/provider/v1/provider.proto
  proto/interchain_security/ccv/provider/v1/query.proto
  proto/interchain_security/ccv/provider/v1/tx.proto
  proto/interchain_security/ccv/v1/ccv.proto
  scripts/protocgen.sh
  x/ccv/consumer/types/consumer.pb.go
  x/ccv/consumer/types/genesis.pb.go
  x/ccv/consumer/types/query.pb.go
  x/ccv/provider/types/genesis.pb.go
  x/ccv/provider/types/provider.pb.go
  x/ccv/provider/types/query.pb.go
  x/ccv/provider/types/tx.pb.go
  x/ccv/types/ccv.pb.go
Labels: A:backport/v3.0.x

#1068 tests: fix broken sovereign app.go
  app/consumer-democracy/app.go
  app/consumer/app.go
  app/provider/app.go
  app/sovereign/app.go
  go.sum
  tests/e2e/actions.go
  tests/e2e/actions_sovereign_chain.go
  tests/e2e/config.go
  tests/e2e/main.go
  tests/e2e/state.go
  tests/e2e/steps_democracy.go
  tests/e2e/steps_reward_denom.go
  tests/e2e/steps_sovereign_changeover.go
  tests/e2e/testnet-scripts/sovereign-genesis.json
Labels: A:backport/v3.0.x

#1090 refactor: log when constructing IBC err ack
  tests/integration/slashing.go
  x/ccv/consumer/ibc_module.go
  x/ccv/consumer/keeper/relay_test.go
  x/ccv/provider/ibc_module.go
  x/ccv/provider/keeper/relay.go
  x/ccv/types/utils.go
Labels: A:backport/v2.0.x, A:backport/v3.0.x

#1093 fix: make SlashPacketData backward compatible when sending data over the wire
  proto/interchain_security/ccv/v1/ccv.proto
  tests/integration/throttle.go
  x/ccv/provider/ibc_module.go
  x/ccv/provider/ibc_module_test.go
  x/ccv/provider/proposal_handler_test.go
  x/ccv/types/ccv.go
  x/ccv/types/ccv.pb.go
Labels: bug, A:backport/v3.0.x

#1108 chore: update CHANGELOG.md for v3
  CHANGELOG.md
Labels: A:backport/v3.0.x
