Repository cosmos/interchain-security, pull requests merged in 2024-01, with the labels that each got.

#1534 test: Add backtransform functionality to genesis transform cli
  app/consumer/genesis.go
  app/consumer/genesis_test.go
  docs/docs/consumer-development/consumer-genesis-transformation.md
  docs/docs/validators/changeover-procedure.md
Labels: C:Testing, C:Docs

#1513 docs: Documentation Enhancements and Code Command Correction in ADR Files
  TESTING.md
  docs/docs/adrs/adr-001-key-assignment.md
  docs/docs/adrs/adr-008-throttle-retries.md
  docs/docs/adrs/adr-010-standalone-changeover.md
  tests/e2e/README.md
Labels: C:Testing, C:Docs, C:ADR

#1503 feat: Add `QueryAllPairsValConAddrByConsumerChainID`
  .changelog/unreleased/improvements/provider/1503-query-key-assignment.md
  docs/docs/features/key-assignment.md
  proto/interchain_security/ccv/provider/v1/query.proto
  tests/e2e/tracehandler_testdata/changeover.json
  tests/e2e/tracehandler_testdata/consumer-double-sign.json
  tests/e2e/tracehandler_testdata/consumer-misbehaviour.json
  tests/e2e/tracehandler_testdata/democracy.json
  tests/e2e/tracehandler_testdata/democracyRewardsSteps.json
  tests/e2e/tracehandler_testdata/happyPath.json
  tests/e2e/tracehandler_testdata/multipleConsumers.json
  tests/e2e/tracehandler_testdata/shorthappy.json
  tests/e2e/tracehandler_testdata/slashThrottle.json
  x/ccv/provider/client/cli/query.go
  x/ccv/provider/keeper/grpc_query.go
  x/ccv/provider/keeper/grpc_query_test.go
  x/ccv/provider/types/query.pb.go
  x/ccv/provider/types/query.pb.gw.go
Labels: C:Testing, C:x/provider, C:Docs, A:backport/v3.3.x

#1549 fix!: Avoid immediately jailing validators that are no longer opted-out
  .changelog/unreleased/bug-fixes/consumer/1549-soft-opt-out.md
  .changelog/unreleased/state-breaking/consumer/1549-soft-opt-out.md
  proto/interchain_security/ccv/consumer/v1/consumer.proto
  tests/integration/common.go
  tests/integration/slashing.go
  tests/integration/soft_opt_out.go
  tests/integration/throttle.go
  tests/integration/throttle_retry.go
  testutil/integration/debug_test.go
  testutil/keeper/mocks.go
  x/ccv/consumer/keeper/soft_opt_out.go
  x/ccv/consumer/module.go
  x/ccv/consumer/types/consumer.pb.go
  x/ccv/consumer/types/validator.go
  x/ccv/types/expected_keepers.go
Labels: C:Testing, C:x/consumer, C:x/types

#1541 chore: fix dockerfile FROM statement
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.gaia
Labels: C:x/provider, C:Build, C:CI

#1557 chore!: bump go to 1.21
  .changelog/unreleased/dependencies/1557-bump-go.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/manual-e2e.yml
  .github/workflows/nightly-e2e.yml
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.gaia
  README.md
  RELEASES.md
  go.mod
  go.sum
Labels: C:Build, C:CI

#1560 test: Fix gosec errors in mbt
  tests/mbt/driver/core.go
  tests/mbt/driver/setup.go
  tests/mbt/driver/trace_gen.go
Labels: C:Testing

#1562 chore: add v4.0.x to mergify and dependabot
  .github/dependabot.yml
  .mergify.yml
Labels: C:CI

#1563 docs: update upgrading instructions
  UPGRADING.md
Labels: A:backport/v4.0.x

#1575 chore: add version linker flags to make install
  Makefile
Labels: enhancement, C:Build, S: ImprovingThings, A:backport/v4.0.x

#1570 fix!: Validation of SlashAcks fails due to marshaling to Bech32
  .changelog/unreleased/bug-fixes/1570-slashack-bech32.md
  .changelog/unreleased/state-breaking/1570-slashack-bech32.md
  .github/workflows/manual-e2e.yml
  .github/workflows/nightly-e2e.yml
  UPGRADING.md
  app/consumer-democracy/app.go
  app/consumer/ante/disabled_modules_ante_test.go
  app/consumer/ante/msg_filter_ante_test.go
  app/consumer/app.go
  app/encoding/encoding.go
  app/params/config.go
  app/params/doc.go
  app/params/encoding.go
  app/params/params.go
  app/params/weights.go
  app/provider/app.go
  app/sovereign/app.go
  cmd/interchain-security-cd/cmd/root.go
  cmd/interchain-security-cd/main.go
  cmd/interchain-security-cdd/cmd/root.go
  cmd/interchain-security-cdd/main.go
  cmd/interchain-security-pd/cmd/root.go
  cmd/interchain-security-pd/main.go
  cmd/interchain-security-sd/cmd/root.go
  cmd/interchain-security-sd/main.go
  tests/e2e/actions.go
  tests/e2e/config.go
  tests/e2e/main.go
  tests/e2e/state.go
  tests/e2e/steps.go
  tests/e2e/steps_consumer_misbehaviour.go
  tests/e2e/steps_downtime.go
  tests/e2e/steps_start_chains.go
  tests/e2e/testnet-scripts/fork-consumer.sh
  tests/e2e/testnet-scripts/sovereign-genesis.json
  x/ccv/consumer/keeper/keeper.go
  x/ccv/consumer/keeper/relay.go
  x/ccv/consumer/keeper/relay_test.go
  x/ccv/consumer/keeper/validators.go
  x/ccv/types/utils.go
  x/ccv/types/wire.go
  x/ccv/types/wire_test.go
Labels: C:Testing, C:x/consumer, C:x/types, C:CI, A:backport/v4.0.x

#1486 test: e2e initialization
  Dockerfile.combined
  tests/e2e/README.md
  tests/e2e/actions.go
  tests/e2e/actions_sovereign_chain.go
  tests/e2e/builder.go
  tests/e2e/config.go
  tests/e2e/main.go
  tests/e2e/state.go
  tests/e2e/test_driver.go
  tests/e2e/test_runner.go
  tests/e2e/test_target.go
  tests/e2e/testnet-scripts/start-docker.sh
Labels: C:Testing, C:Build

#1595 test: Fix e2e tests for changeover
  tests/e2e/actions_sovereign_chain.go
Labels: C:Testing

#1573 test: add key assignment to model and driver
  Makefile
  tests/mbt/driver/core.go
  tests/mbt/driver/generate_more_traces.sh
  tests/mbt/driver/generate_traces.sh
  tests/mbt/driver/mbt_test.go
  tests/mbt/driver/stats.go
  tests/mbt/model/README.md
  tests/mbt/model/ccv.qnt
  tests/mbt/model/ccv_boundeddrift.qnt
  tests/mbt/model/ccv_model.qnt
  tests/mbt/model/ccv_test.qnt
  tests/mbt/model/ccv_utils.qnt
  tests/mbt/run_invariants.sh
Labels: C:Testing, C:Build

#1593 ci: GH workflow for publishing docker images
  .github/workflows/docker-publish.yml
Labels: C:CI, A:backport/v3.2.x, A:backport/v4.0.x, A:backport/v3.3.x

#1584 docs: add ADR for Partial Set Security
  docs/docs/adrs/adr-015-partial-set-security.md
  docs/docs/adrs/intro.md
Labels: C:Docs, C:ADR

#1605 feat: Added query for provider parameters
  .changelog/unreleased/improvements/provider/1445-query-provider-parameters.md
  proto/interchain_security/ccv/provider/v1/query.proto
  x/ccv/provider/client/cli/query.go
  x/ccv/provider/keeper/grpc_query.go
  x/ccv/provider/types/query.pb.go
  x/ccv/provider/types/query.pb.gw.go
Labels: C:x/provider, S: ImprovingThings, A:backport/v4.0.x, A:backport/v3.3.x
