Repository cosmos/interchain-security, pull requests merged in 2025-03, with the labels that each got.

#2559 chore(deps): bump ibc-go to v10.0.0-rc.3
  app/consumer-democracy/app.go
  app/consumer/app.go
  app/provider/app.go
  app/sovereign/app.go
  go.mod
  go.sum
  tests/interchain/go.mod
  tests/interchain/go.sum
  x/ccv/provider/ibc_module_test.go
  x/ccv/provider/module_test.go
Labels: C:Testing, C:x/provider

#2560 chore: Update mergify config
  .mergify.yml
Labels: C:CI

#2565 chore: Bump ibc-go version
  go.mod
  go.sum
  tests/interchain/go.mod
  tests/interchain/go.sum
Labels: C:Testing
